# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]


# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# Middleman Gems
gem "middleman"
gem "middleman-blog"
# gem 'middleman-search' # https://github.com/manastech/middleman-search

gem "middleman-syntax"

# gem 'redcarpet', '~> 3.3', '>= 3.3.3'

# For feed.xml.builder
gem "builder", "~> 3.0"

gem 'middleman-deploy', '~> 2.0.0.pre.alpha'


# adds password protection
# https://github.com/ahoward/middleman-gibberish
# gem "middleman-gibberish"
gem 'middleman-gibberish', :git => 'https://github.com/ahoward/middleman-gibberish.git'

# https://github.com/janson/presentation-middleman

# https://github.com/dsedivec/middleman-related-articles

# https://github.com/statonjr/middleman-sitemap

# fix tilt issues
gem 'opal', '~> 0.10.5' 

